### ISSUE TITLE
Unable to search for PowerShell cmdlet in verb-noun format

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#100]
Searching for "New-BrokerMachine" even in quotes returns results for "BrokerMachine" making it very difficult to find what I want - I get 530 results

![image](https://user-images.githubusercontent.com/11651939/190221682-bac2d793-d6b8-4ab7-9613-6a8cb6bafefa.png)

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/MachineCreation/New-ProvVM/

**Comment by katshann** [comment]
Hello. Thanks for your feedback. I'll raise this with the team and see what can be done. Cheers!

**Comment by katshann** [comment]
Hi Guy,
The CVAD SDK docs have been moved to a new platform. From the looks of it the search is a little more discerning on the new platform:
![image](https://github.com/citrix/devdocs-issue-collector/assets/6401412/b6f170b1-e836-41f1-8d13-88503ac3e895)
Give it a try at https://developer-docs.citrix.com/en-us/citrix-virtual-apps-desktops-sdk/current-release/ and see if it fits your purposes.
I'm going to close this ticket as we are no longer tracking feedback here on GitHub, If you have feedback on the new site, the articles all have a "Send us your feedback" button on the left (same as the product documentation). 
Cheers,
Kat
