### ISSUE TITLE
Invalid shortcut

### ISSUE THREAD

**Issue by syph00n** [citrix/devdocs-issue-collector#102]
The following shortcut on the page doesn't work: 

**Follow how to** [use PowerShell SDKs](https://developer-docs.citrix.com/projects/citrix-daas/en/latest/group-policy-sdk-usage/#citrix-group-policy-provider)

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/

**Comment by katshann** [comment]
Hello. This link should now be working on the live page, Cheers!
