### ISSUE TITLE
Link on page leads to 404

### ISSUE THREAD

**Issue by ZeffyReport** [citrix/devdocs-issue-collector#103]
[Provide your feedback here]
'Use PowerShell SDKs' link (https://developer-docs.citrix.com/projects/citrix-daas/en/latest/group-policy-sdk-usage/#citrix-group-policy-provider) leads to page not found, so needs correcting.

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/

**Comment by katshann** [comment]
Hello. Thank you for your feedback. I'll look at getting this fixed ASAP. Cheers!

**Comment by katshann** [comment]
Links should no longer be broken.
