### ISSUE TITLE
Missing links for "See about_Broker_Filtering"

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#107]
It would make it much easier to use if all the references to "See about_Broker_Filtering" in the body of the article were hyperlinks which they are not

Docs URL:https://developer-docs.citrix.com/projects/delivery-controller-sdk/en/latest/Broker/Get-BrokerMachine/

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
