### ISSUE TITLE
VDA Type Supported?

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#110]
[Provide your feedback here]
For on-premises, are only multi-session VDAs supported? In on-prem Studio, for single-session VDAs, there is no Restart Schedule option, unlike DaaS.

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/Start-BrokerRebootCycle/

**Comment by katshann** [comment]
Hi Carl,
I have been advised that while the on-prem Studio does not surface the capability, restart schedules are supported for OnPrem single-session VDAs and this feature can be used through the SDK.
Cheers,
Kat
