### ISSUE TITLE
Bad formatting

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#111]
[Provide your feedback here]
The examples are not formatted properly. There are two <br><br> in each example.

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/MachineCreation/Get-ProvScheme/

**Comment by katshann** [comment]
Hi Carl,
Thanks for your feedback. We have an initiative to improve the formatting of the DaaS/CVAD docs that is with the team. This should include fixing the issue with the example formatting. I'll make sure that this ticket is linked to that one.
Cheers,
Kat

Internal ref: BRK-12080

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
