### ISSUE TITLE
about_ProvCustomProperties

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#112]
[Provide your feedback here]
CustomProperties <string> Properties of the provisioning scheme which that are specific to the target hosting infrastructure. (See about_ProvCustomProperties)

Why is "about_ProvCustomProperties" not a clickable link? I see no way to find that in the cmdlet docs. Where is it?

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/MachineCreation/Get-ProvScheme/#citrixmachinecreationsdkprovisioningscheme

**Comment by katshann** [comment]
Hi Carl,
I believe the page in question can be found here: https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/MachineCreation/about_Prov_CustomProperties/  
I'll raise a ticket with the team responsible for these docs and see if I can get the various "See ..." text turned into links.
Cheers,
Kat

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
Internal reference: BRK-10702
