### ISSUE TITLE
No reference for -CommandName or -Category

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#117]
Needs to be a reference or method to find out what are legal values to the -CommandName and -Category parameters

Docs URL:https://developer-docs.citrix.com/projects/delivery-controller-sdk/en/latest/Broker/New-BrokerMachineCommand/

**Comment by katshann** [comment]
Hello,
I've raised an internal ticket to have this info fleshed out and improved. Thanks for the feedback. 
Cheers,
Kat

Ref: BRK-14325

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
However, the XAXD 7.15 version of the docs that you reference in the ticket is not available at the new location: https://developer-docs.citrix.com/en-us/citrix-virtual-apps-desktops-sdk/current-release.html  I believe the 7.15 version is now EoL,
Cheers,
Kat
