### ISSUE TITLE
IdentityPoolName and NamingScheme parameters text spills over into Required column

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#118]
IdentityPoolName and NamingScheme parameters text spills over into Required column

This is with Edge 109.0.1518.61 on Win11 

Happens on many of these cmdlet pages

![image](https://user-images.githubusercontent.com/11651939/214885464-e7e11cca-e516-4f17-97dc-d88205180ce0.png)

Docs URL:https://developer-docs.citrix.com/projects/delivery-controller-sdk/en/latest/ADIdentity/New-AcctIdentityPool/

**Comment by katshann** [comment]
Hi Guy, 
Thanks for your feedback. While there have been some formatting and table layout improvements in more recent versions of the the docs, it looks like this isn't one of them :( (https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/ADIdentity/New-AcctIdentityPool/).
We are working through these formatting issues and there are some existing internal cases and initiatives that can lead to improvements in future versions of these docs. However, these changes may not be propagated back to the older docsets like XAXD 7.15.
Cheers,
Kat

Ref: BRK-12080

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally. This issue is not yet fixed in the new site.
Cheers,
Kat
