### ISSUE TITLE
HTML rendering issues

### ISSUE THREAD

**Issue by ehrenfeu** [citrix/devdocs-issue-collector#119]
Plenty of broken HTML tags shown as plain text: `&gt;` instead of `>` etc.

Makes the whole page unreadable.

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/about_Broker_Filtering/

**Comment by katshann** [comment]
Hello @ehrenfeu 

Thank you for your feedback. I've made some updates. Hopefully, these filtering topics are now a little more readable. 

Cheers,
Kat
