### ISSUE TITLE
Says DesktopKind is Deprecated and to use AllocationType but that is not documented

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#120]
"DesktopKind (Citrix.Broker.Admin.SDK.DesktopKind) Deprecated. Denotes whether the desktop is private or shared. AllocationType should be used instead."

AllocationType is not documented on this page

Docs URL:https://developer-docs.citrix.com/projects/delivery-controller-sdk/en/latest/Broker/Get-BrokerDesktop/

**Comment by katshann** [comment]
Hello,
Thanks for your feedback. I've raised a ticket for the team to document the preferred parameter.
Cheers,
Kat

Ref: BRK-14321

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
