### ISSUE TITLE
Related command listed is Get-LogLowLevelOperation which this page is for

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#121]
The only related command listed is the same as the page is for so isn't a related command as such

Docs URL:https://developer-docs.citrix.com/projects/delivery-controller-sdk/en/latest/ConfigLogging/Get-LogLowLevelOperation/

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat

Internal reference: BRK-14320
