### ISSUE TITLE
Source example of "Desktop Studio" does not work

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#122]
The correct source is "Studio" not "Desktop Studio"

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/1808/ConfigurationLogging/Get-LogHighLevelOperation/

**Comment by katshann** [comment]
Hello,
My apologies for the delayed response. I've raised an internal ticket for our team to address this issue.
Cheers,
Kat

Ref: BRK-14319

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
However, the 1808 version of the SDK docs  that you reference in this ticket is no longer available at the new location: https://developer-docs.citrix.com/en-us/citrix-virtual-apps-desktops-sdk  I believe this version is EoL.
Cheers,
Kat
