### ISSUE TITLE
Placeholders in document

### ISSUE THREAD

**Issue by bethp25** [citrix/devdocs-issue-collector#13]
There are placeholders in this article that say FIXME.

Please correct and update.

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Monitor/Get-MonitorConfiguration/

**Comment by davidgreen99** [comment]
Emailed @himanshua or @vikramjeets for assistance.

**Comment by davidgreen99** [comment]
PINGED reminder email 6/5/21

**Comment by katshann** [comment]
Chased internally (DIR-15240)

**Comment by katshann** [comment]
Update to URL where problem seen:
https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/Monitor/Get-MonitorConfiguration/
Not fixed in 2203. Will chase.

**Comment by katshann** [comment]
Hello Beth, 

Hope life's treating you well. :) Looks like the FIXME items have been removed in the latest version of the docs so I shall close the ticket.

Cheers,
Kat
