### ISSUE TITLE
Get-HypInventoryItem

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#134]
[Provide your feedback here]
Where do I find this cmdlet?

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\ctxadmin> Get-XDAuthentication -ProfileName "Default"
>> add-pssnapin "Citrix.Common.GroupPolicy"
>> Import-Module "Citrix.ADIdentity.Commands"
>> Import-Module "Citrix.Analytics.Commands"
>> Import-Module "Citrix.AppLibrary.Commands"
>> Import-Module "Citrix.Broker.Commands"
>> Import-Module "Citrix.Common.Commands"
>> Import-Module "Citrix.Configuration.Commands"
>> Import-Module "Citrix.ConfigurationLogging.Commands"
>> Import-Module "Citrix.DelegatedAdmin.Commands"
>> If(Test-Path XDHyp:)
>> {
>>     Remove-PSDrive -Name XDHyp
>> }
>> Import-Module "Citrix.Host.Commands"
>> Import-Module "Citrix.MachineCreation.Commands"
>> Import-Module "Citrix.Monitor.Commands"
>> Import-Module "Citrix.Storefront.Commands"
WARNING: The names of some imported commands from the module 'Citrix.MachineCreation.Commands' include unapproved verbs
 that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command
again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
PS C:\Users\ctxadmin> Get-HypInventoryItem -LiteralPath "XDHyp:\hostingunits\Remko-EC2-US-West2-Subnet-2D" -ResourceType template -MaxRecords 999
**Get-HypInventoryItem : The term 'Get-HypInventoryItem' is not recognized as the name of a cmdlet**, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ Get-HypInventoryItem -LiteralPath "XDHyp:\hostingunits\Remko-EC2-US-W ...
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-HypInventoryItem:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\ctxadmin> get-command get-hyp*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-HypConfigurationDataForItem                    2.0        Citrix.Host.Commands
Cmdlet          Get-HypConfigurationObjectForItem                  2.0        Citrix.Host.Commands
Cmdlet          Get-HypConnectionRegion                            2.0        Citrix.Host.Commands
Cmdlet          Get-HypDBConnection                                2.0        Citrix.Host.Commands
Cmdlet          Get-HypDBSchema                                    2.0        Citrix.Host.Commands
Cmdlet          Get-HypDBVersionChangeScript                       2.0        Citrix.Host.Commands
Cmdlet          Get-HypHypervisorPlugin                            2.0        Citrix.Host.Commands
Cmdlet          Get-HypInstalledDBVersion                          2.0        Citrix.Host.Commands
Cmdlet          Get-HypLocalizedString                             2.0        Citrix.Host.Commands
Cmdlet          Get-HypPvsDiskInfo                                 2.0        Citrix.Host.Commands
Cmdlet          Get-HypPvsSite                                     2.0        Citrix.Host.Commands
Cmdlet          Get-HypPvsStore                                    2.0        Citrix.Host.Commands
Cmdlet          Get-HypScopedObject                                2.0        Citrix.Host.Commands
Cmdlet          Get-HypService                                     2.0        Citrix.Host.Commands
Cmdlet          Get-HypServiceAddedCapability                      2.0        Citrix.Host.Commands
Cmdlet          Get-HypServiceInstance                             2.0        Citrix.Host.Commands
Cmdlet          Get-HypServiceStatus                               2.0        Citrix.Host.Commands
Cmdlet          Get-HypVMMacAddress                                2.0        Citrix.Host.Commands
Cmdlet          Get-HypVolumeServiceConfiguration                  2.0        Citrix.Host.Commands
Cmdlet          Get-HypXenServerAddress                            2.0        Citrix.Host.Commands

PS C:\Users\ctxadmin>

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/HostService/Get-HypInventoryItem/

**Comment by CarlWebster** [comment]
I found it. I needed to update to the May 18th Remote SDK version.

PS C:\Users\ctxadmin> Get-HypInventoryItem -LiteralPath "XDHyp:\hostingunits\Remko-EC2-US-West2-Subnet-2D" -ResourceType template -MaxRecords 999
Get-HypInventoryItem : Attempts to perform the operation failed. The Hypervisor does not support filtering or
pagination of inventory items.
At line:1 char:1
+ Get-HypInventoryItem -LiteralPath "XDHyp:\hostingunits\Remko-EC2-US-W ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-HypInventoryItem], InvalidOperationException
    + FullyQualifiedErrorId : Citrix.XDPowerShell.HostStatus.FilteredGetItemNotSupported,Citrix.Host.Sdk.Commands.GetH
   ypInventoryItemCommand

PS C:\Users\ctxadmin>

Thanks


Carl Webster
Citrix Technology Professional Fellow | IGEL VIP | Parallels VIPP | VMware vExpert 2023 |VMware vExpert EUC 2023 | VMware Influencer 100
http://www.CarlWebster.com<https://carlwebster.com/>
The Accidental Citrix Admin

From: Carl Webster ***@***.***>
Sent: Tuesday, May 30, 2023 5:00 PM
To: citrix/devdocs-issue-collector ***@***.***>
Cc: Webster ***@***.***>; Your activity ***@***.***>
Subject: [citrix/devdocs-issue-collector] Get-HypInventoryItem (Issue #134)


[Provide your feedback here]
Where do I find this cmdlet?

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\ctxadmin> Get-XDAuthentication -ProfileName "Default"

add-pssnapin "Citrix.Common.GroupPolicy"
Import-Module "Citrix.ADIdentity.Commands"
Import-Module "Citrix.Analytics.Commands"
Import-Module "Citrix.AppLibrary.Commands"
Import-Module "Citrix.Broker.Commands"
Import-Module "Citrix.Common.Commands"
Import-Module "Citrix.Configuration.Commands"
Import-Module "Citrix.ConfigurationLogging.Commands"
Import-Module "Citrix.DelegatedAdmin.Commands"
If(Test-Path XDHyp:)
{
Remove-PSDrive -Name XDHyp
}
Import-Module "Citrix.Host.Commands"
Import-Module "Citrix.MachineCreation.Commands"
Import-Module "Citrix.Monitor.Commands"
Import-Module "Citrix.Storefront.Commands"
WARNING: The names of some imported commands from the module 'Citrix.MachineCreation.Commands' include unapproved verbs
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command
again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
PS C:\Users\ctxadmin> Get-HypInventoryItem -LiteralPath "XDHyp:\hostingunits\Remko-EC2-US-West2-Subnet-2D" -ResourceType template -MaxRecords 999
Get-HypInventoryItem : The term 'Get-HypInventoryItem' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1

  *   Get-HypInventoryItem -LiteralPath "XDHyp:\hostingunits\Remko-EC2-US-W ...

·           + CategoryInfo          : ObjectNotFound: (Get-HypInventoryItem:String) [], CommandNotFoundException

·           + FullyQualifiedErrorId : CommandNotFoundException

·

  *

PS C:\Users\ctxadmin> get-command get-hyp*

CommandType Name Version Source

________________________________

Cmdlet Get-HypConfigurationDataForItem 2.0 Citrix.Host.Commands
Cmdlet Get-HypConfigurationObjectForItem 2.0 Citrix.Host.Commands
Cmdlet Get-HypConnectionRegion 2.0 Citrix.Host.Commands
Cmdlet Get-HypDBConnection 2.0 Citrix.Host.Commands
Cmdlet Get-HypDBSchema 2.0 Citrix.Host.Commands
Cmdlet Get-HypDBVersionChangeScript 2.0 Citrix.Host.Commands
Cmdlet Get-HypHypervisorPlugin 2.0 Citrix.Host.Commands
Cmdlet Get-HypInstalledDBVersion 2.0 Citrix.Host.Commands
Cmdlet Get-HypLocalizedString 2.0 Citrix.Host.Commands
Cmdlet Get-HypPvsDiskInfo 2.0 Citrix.Host.Commands
Cmdlet Get-HypPvsSite 2.0 Citrix.Host.Commands
Cmdlet Get-HypPvsStore 2.0 Citrix.Host.Commands
Cmdlet Get-HypScopedObject 2.0 Citrix.Host.Commands
Cmdlet Get-HypService 2.0 Citrix.Host.Commands
Cmdlet Get-HypServiceAddedCapability 2.0 Citrix.Host.Commands
Cmdlet Get-HypServiceInstance 2.0 Citrix.Host.Commands
Cmdlet Get-HypServiceStatus 2.0 Citrix.Host.Commands
Cmdlet Get-HypVMMacAddress 2.0 Citrix.Host.Commands
Cmdlet Get-HypVolumeServiceConfiguration 2.0 Citrix.Host.Commands
Cmdlet Get-HypXenServerAddress 2.0 Citrix.Host.Commands

PS C:\Users\ctxadmin>

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/HostService/Get-HypInventoryItem/

**Comment by katshann** [comment]
Hi Carl,
Sorry for the delay in response. Sounds like you've sorted this issue now? I'm going to close this ticket, but please reopen and let me know if there's action needed on our side.
Cheers,
Kat
