### ISSUE TITLE
No dark mode option

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#136]
Other Citrix documentation sites/pages have a dark mode switch in the top right hand corner

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/

**Comment by katshann** [comment]
Hi Guy,

The product documentation and developer documentation are currently built and hosted differently. While the product docs have a dark mode, the developer docs do not. 
We are making some changes to the developer-docs at the moment. While I don't know and can't give any specifics with regards to features and timelines, I'm fairly sure that the site will have a dark mode soon. 
I'm checking that statement with a colleague and will let you know if I've spoken in error.

Cheers,
Kat

**Comment by katshann** [comment]
Hi Guy, 
The migration of these docs to the new publishing platform is complete and a dark mode is now available for the Citrix DaaS SDK docs.
Cheers,
Kat
