### ISSUE TITLE
Tells you to use PowerShell 3.0

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#137]
Document says:

Start a shell in PowerShell 3.0.

PowerShell 4.0 was released about 10 years ago. There's no reason to use anything other than 5.1 or even don't specify an exact version, just put "Windows PowerShell" given that it still doesn't work with 7.x

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/

**Comment by katshann** [comment]
Hello,
I've raised an internal ticket to pass this concern on to the Engineering team and get it updated.
Cheers,
Kat

Internal reference: BRK-14318

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
