### ISSUE TITLE
INcorrect info

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#138]
[Provide your feedback here]

<html>
<body>

MinimumFunctionalLevel | Gets catalogs with a specific MinimumFunctionalLevel. |   |   |  
-- | -- | -- | -- | --
Valid values are L5, L7, L7_6, L7_7, L7_8, L7_9, L7_20, L7_25 | false | false

</body>
</html>

L7_30 has been available since CVAD 2106.
L7_34 has been available since CVAD 2206.

Why are those not documented?

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/Get-BrokerCatalog/

**Comment by katshann** [comment]
Hello,

Thanks for providing feedback.  I've raised this as an internal ticket for the engineering team.

Cheers,
Kat

Reference: https://issues.citrite.net/browse/BRK-14317

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
