### ISSUE TITLE
AllocationType description is wrong

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#139]
Document says allocation type is either Permanent or Random but there is another option in the cmdlet "Static" which the DaaS cmdlet returns for machines allocated to users

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/Broker/Get-BrokerMachine/

**Comment by katshann** [comment]
Hello, 
Thanks for spotting this. I've raised a ticket in our internal system to get this fixed and the missing info added.
Cheers,
Kat

Reference: BRK-14316

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
