### ISSUE TITLE
Where is the property IdentityType

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#141]
[Provide your feedback here]

From Get-ProvScheme:

IdentityType <string> Identity type used to join created machines to a directory service. (See New-ProvScheme.)

In New-ProvScheme there is no IdentityType property.

I am trying to find this:

> Machine Catalog
Name: JRR-Azure-Win10SingleMCS
Machine Type: Single-session OS (Virtual)
Provisioning Method: Machine creation services (MCS machine)
Provisioning Scheme ID: 7779da55-c89f-4233-9569-e1c699ce010f
Allocation Type: Random
Folder: -
Functional Level: 2106 (or later)
Scopes: All
Tenants: -
Zone: JamesR_2
**Identity Type: Hybrid Azure AD joined**

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/MachineCreation/New-ProvScheme/

**Comment by CarlWebster** [comment]
It is in Get-AcctIdentityPool.

> PS C:\webster> get-acctidentitypool -identitypoolname "JRR-Azure-Win10SingleMCS"


AvailableAccounts    : 0
DeviceManagementType : None
Domain               : JAMESRANKIN.ONMICROSOFT.COM
ErrorAccounts        : 0
IdentityContent      :
IdentityPoolName     : JRR-Azure-Win10SingleMCS
IdentityPoolUid      : af434c1d-cc00-4704-a574-1c0c77ed217c
**IdentityType         : HybridAzureAD**
InUseAccounts        : 1
Lock                 : False
MetadataMap          : {}
NamingScheme         : DTAZ-###
NamingSchemeType     : Numeric
OU                   : OU=Workers,OU=Windows,OU=Devices,DC=jamesrankin,DC=onmicrosoft,DC=com
ResourceLocationId   : 570edf55-be2e-44ad-86d6-dc1f92e7a05f
StartCount           : 2
TaintedAccounts      : 0
WorkgroupMachine     : False
ZoneUid              : 83ae6a34-2c0e-475a-8372-cde02143abb0
Scopes               :
TenantId             :

**Comment by katshann** [comment]
Hi Carl,
thanks for your feedback. Do you happen to know if this means the link in Get_ProvScheme needs to point to Get_AcctIdentityPool article instead of the New_ProvScheme article. Or instead that the info needs to be added to New_ProvScheme article as well? 
Cheers,
Kat

**Comment by CarlWebster** [comment]
Yes, it should point to New-AcctIdentityPool. New-ProvScheme doesn't have an IdentityType property.

It should be:

IdentityType Identity type used to join created machines to a directory service. (See New-AcctIdentityPool.)

The problem is also that neither Get- or New-AcctIdentityPool give any information on the Indentty Type.

IdentityType <string> The identity type.

Where is the info on the possible types?

Switch ($IdentityPool.IdentityType)
{
                "ActiveDirectory"             {$IdentityType = "On-premises AD"; Break}
                "AzureAD"                                          {$IdentityType = "Azure AD joined"; Break}
                "HybridAzureAD"                             {$IdentityType = "Hybrid Azure AD joined"; Break}
                "Workgroup"                                     {$IdentityType = "Non-domain-joined"; Break}
                Default                                                 {$IdentityType = "-"; Break}
}

Thanks


Carl Webster
Citrix Technology Professional Fellow | IGEL VIP | Parallels VIPP | VMware vExpert 2023 |VMware vExpert EUC 2023 | VMware Influencer 100
http://www.CarlWebster.com<https://carlwebster.com/>
The Accidental Citrix Admin

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat

Internal ref: BRK-14541
