### ISSUE TITLE
Where is Get-VusCatalogInfo?

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#142]
[Provide your feedback here]

You are running Remote SDK version 7.38.0.0.

Get-VusCatalogInfo : The term 'Get-VusCatalogInfo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

PS C:\webster> get-command *vus*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Confirm-VusSelection                               1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusAvailableVdaVersion                         1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusCatalog                                     1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusComponents                                  1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusComponentVersion                            1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusDBConnection                                1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusDBSchema                                    1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusDBVersionChangeScript                       1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusEntityUnit                                  1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusInstalledDBVersion                          1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusMachine                                     1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusMachineSchedule                             1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusRevision                                    1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusSchedule                                    1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusService                                     1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusServiceAddedCapability                      1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusServiceInstance                             1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusServiceStatus                               1.0        Citrix.VdaUpdateService.Commands
Cmdlet          New-VusCatalogSchedule                             1.0        Citrix.VdaUpdateService.Commands
Cmdlet          New-VusMachineUpgrade                              1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Remove-VusCatalogUpgrade                           1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Remove-VusMachineUpgrade                           1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Remove-VusServiceMetadata                          1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Reset-VusEnabledFeatureList                        1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Reset-VusServiceGroupMembership                    1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Set-VusCatalogUpgrade                              1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Set-VusCatalogUpgradeType                          1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Set-VusDBConnection                                1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Set-VusMachineUpgrade                              1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Set-VusServiceMetadata                             1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Test-VusDBConnection                               1.0        Citrix.VdaUpdateService.Commands

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/VdaUpdateService/Get-VusCatalogInfo/

**Comment by CarlWebster** [comment]
Any update? This is killing my DaaS documentation script.

**Comment by katshann** [comment]
Hi Carl,
Thanks for the feedback. Let me look into this with the person who manages the DaaS SDK docs. That particular article hasn't been updated for a little while, so it might be that the command was deprecated and removed in the past few months.
Cheers,
Kat

**Comment by CarlWebster** [comment]
WELL CRAP! That's not good.


Thanks


Carl Webster
Citrix Technology Professional Fellow | IGEL VIP | Parallels VIPP | VMware vExpert 2023 |VMware vExpert EUC 2023 | VMware Influencer 100
http://www.CarlWebster.com<https://carlwebster.com/>
The Accidental Citrix Admin

**Comment by katshann** [comment]
Ooops - didn't mean to be alarmist - that's just my uneducated guess about what might have happened. I'm by no means an expert. Hopefully confirmation one way or another will be available soon.

**Comment by katshann** [comment]
Hello,

The engineering team provided the following info:
"These cmdlets are being retired. We are removing these retired cmdlets from docs in upcoming release.
 Get-VusMachine and Get-VusCatalog are the alternatives."
Hopefully, you can adapt your script accordingly. :)

Cheers,
Kat

**Comment by CarlWebster** [comment]
I will work on it when I get home from NYC and let you know how it went.

**Comment by CarlWebster** [comment]
In my opinion, Citrix has castrated/broken/ruined this capability. Get-VusCatalog and Get-VusMachine don't provide the necessary info or any info related to the VDA Upgrade Service.

If these cmdlets are no longer available - with absolutely NO notification - but still documented, couldn't you at least provide the process of using Get-VusCatalog and Get-VusMachine to replace what Get-VusCatalogInfo and Get-VusMachineInfo provided?

I am sorry, but this is just STUPID. Remove two cmdlets with no warning, and you don't document what to do to get the same data. Stupid. I mean, I retire in eight days and now I have to remove two sections of the DaaS documentation script because someone made the bone-headed decision to pull this crap.

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally. The VUS team have said they will remove these mistakenly published command shortly. For now, they are still visible: https://developer-docs.citrix.com/en-us/citrix-daas-sdk/VdaUpdateService/Get-VusCatalogInfo/ 
Cheers,
Kat
