### ISSUE TITLE
Incorrect return data

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#143]
[Provide your feedback here]

NamingSchemeType <string>
    The naming scheme type for the identity pool. This can be one of the following:
        Numeric - naming scheme uses numeric indexes
        Alphabetic - naming scheme uses alphabetic indexes

What about None?

> PS C:\webster> Get-AcctIdentityPool |select namingschemetype

NamingSchemeType
----------------
         Numeric
         Numeric
         Numeric
         Numeric
         Numeric
         Numeric
         Numeric
         Numeric
         Numeric
         Numeric
         Numeric
            None
         Numeric
         Numeric
         Numeric
         Numeric
         Numeric

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/ADIdentity/Get-AcctIdentityPool/

**Comment by katshann** [comment]
Hi Carl,
thanks for teh feedback. I've raised a ticket to request that this information be added to the docs.
Cheers,
Kat

Ref: BRK-14381

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
