### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#144]
[Provide your feedback here]

WindowsActivationType <string> Windows Activation Type set on the Master Image which has a mapping with the Provisioning Scheme.This feature is supported from 2303 and successive VDA v

The information is cut off on the right side of the screen.

Also, what are the possible values?

> PS C:\webster> get-provscheme |select WindowsActivationType

WindowsActivationType
---------------------
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA
UnsupportedVDA

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/MachineCreation/Get-ProvScheme/

**Comment by katshann** [comment]
Hi Carl,

The information that is clipped off the screen is:

>WindowsActivationType <string> Windows Activation Type set on the Master Image which has a mapping with the Provisioning Scheme.This feature is supported from 2303 and successive VDA versions. Any previous VDA version or if the vda is not of Windows Operating System Type, the field would be "UnsupportedVDA" 

(Sometimes if the formatting is off in the DaaS SDK docs, the equivalent CVAD SDK article shows it better,)

I appreciate this probably doesn't answer your question about all the possible values, so I'll raise the question with the Engineering Team.

Cheers,
Kat

**Comment by katshann** [comment]
Internal ref for formatting issue: BRK-14380

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Unfortunately, the new platform still has the display issue as this originates in the source, not the publishing platform. 
For now, the equivalent CVAD page does correctly display: https://developer-docs.citrix.com/en-us/citrix-virtual-apps-desktops-sdk/current-release/MachineCreation/Get-ProvScheme.html
Cheers,
Kat
