### ISSUE TITLE
I am getting failures when running "New-AcctADAccount" command. I tried in 2-3 Citrix Cloud environments but the result is same. There is no event log or CDF trace information .

### ISSUE THREAD

**Issue by amalkabraham001** [citrix/devdocs-issue-collector#145]
[Provide your feedback here]

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/ADIdentity/New-AcctADAccount/

New-AcctADAccount -Count $VDICount -IdentityPoolUid $IdentityPool -ErrorAction Stop -ADUserName ",mydomain\admin" -ADPassword $password -OutVariable result

[6:46](https://citrixcta.slack.com/archives/C44UTE3HU/p1686748611619009)
SuccessfulAccounts SuccessfulAccountsCount FailedAccountsCount FailedAccounts
------------------ ----------------------- ------------------- --------------
{}                                       0                   1 {CTXADVDI002}

**Comment by katshann** [comment]
Hello,
Given the lack of any log or trace information being produced by the command, you might have more luck getting this addressed by contacting our Technical Support department at https://www.citrix.com/support/open-a-support-case/
Many thanks,
Kat
