### ISSUE TITLE
Protocol Priority

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#146]
[Provide your feedback here]

<html>
<body>

ProtocolPriority | A list of protocol names in the order in which they should be attempted for use during connection.
-- | --

</body>
</html>

And the possible protocol options are, what?

Neither of these have the info either.

[Get-BrokerDesktopGroup](https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/Broker/Get-BrokerDesktopGroup/)
[New-BrokerDesktopGroup](https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/Broker/New-BrokerDesktopGroup/)

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/Broker/Set-BrokerDesktopGroup/

**Comment by katshann** [comment]
Hi Carl,
I've raised a ticket to add more information to these docs and will see if I can get an answer in the mean time.
Cheers,
Kat

Internal reference: BRK-14382

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
