### ISSUE TITLE
Missing cmdlet?

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#147]
[Provide your feedback here]

What happened to this cmdlet?

Get-VusMachineInfo : The term 'Get-VusMachineInfo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.

> PS C:\webster> get-command get-vus*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-VusAvailableVdaVersion                         1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusCatalog                                     1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusComponents                                  1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusComponentVersion                            1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusDBConnection                                1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusDBSchema                                    1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusDBVersionChangeScript                       1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusEntityUnit                                  1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusInstalledDBVersion                          1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusMachine                                     1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusMachineSchedule                             1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusRevision                                    1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusSchedule                                    1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusService                                     1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusServiceAddedCapability                      1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusServiceInstance                             1.0        Citrix.VdaUpdateService.Commands
Cmdlet          Get-VusServiceStatus                               1.0        Citrix.VdaUpdateService.Commands

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/VdaUpdateService/Get-VusMachineInfo/

**Comment by katshann** [comment]
Hello,

The engineering team provided the following info:
"These cmdlets are being retired. We are removing these retired cmdlets from docs in upcoming release.
 Get-VusMachine and Get-VusCatalog are the alternatives."
Hopefully, you can adapt your script accordingly. :)

Cheers,
Kat

**Comment by CarlWebster** [comment]
In my opinion, Citrix has castrated/broken/ruined this capability. Get-VusCatalog doesn't provide the necessary info or any info related to the VDA Upgrade Service.

If these cmdlets are no longer available - with absolutely NO notification - but still documented, couldn't you at least provide the process of using Get-VusCatalog to replace what Vet-VusCatalogInfo provided?

I am sorry, but this is just STUPID. Remove two cmdlets with no warning, and you don't document what to do to get the same data. Stupid. I mean, I retire in eight days and now I have to remove a section of the DaaS documentation script because someone made the bone-headed decision to pull this crap.
