### ISSUE TITLE
MDMEnrollment

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#148]
[Provide your feedback here]

Is this property working for Machine Catalogs?

MdmEnrollment (System.String) Indicates the MdmEnrollment of the catalog. Possible values:

None: No Mdm.
Intune: Microsoft Intune.
IntuneWithCitrixTags: Microsoft Intune with Citrix tags.

I have someone who ran my updated DaaS documentation script where catalogs are configured for Intune, but the MDMEnrollment property shows None, but Get-AcctIdentityPool shows Intune.

> 

Description | -
-- | --
Account naming scheme | AACTXVDA####
AD Domain |  
AD Location |  
Allocated machines | 1
Allocation type | Permanent
Clean on Boot | False
Dedicated Tenancy | False
Description | -
**Device Management Type | Microsoft Intune**
Disk Image | Citrix_MCSAAD_Mastervm_12062023
Hard disk | 32 GB
Identity Pool Name | Amal-AzureAD-DedicatedSS
Identity Type | Azure AD joined
Installed VDA version | 2203.0.3000.3261
Machine Type | Single-session OS (Virtual)
Master Image VM | Citrix_MCSAAD_Mastervm_12062023.snapshot
Master Image VM Date | Mon Jun 12 21:34:18 2023
**MDM Enrollment | No MDM**

</body>
</html>

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/Broker/Get-BrokerCatalog/

**Comment by katshann** [comment]
Hi Carl,
I've raised this as an internal case for teh engineers to investigate.
Cheers,
Kat

Reference: BRK-14444

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
