### ISSUE TITLE
Edge Servers and Healthy ZOne

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#149]
[Provide your feedback here]

<html>
<body>

HasValidEdgeServers | Gets zones with the specified value of the HasValidEdgeServers property. | false | false |  
IsHealthy | Gets zones with the specified value of the IsHealthy property. | false | false

<br class="Apple-interchange-newline">
</body>
</html>

What is a valid edge server? What is an invalid edge server? How do I resolve having invalid edge servers? What makes a zone healthy? What makes a zone unhealthy? How do I resolve or fix an unhealthy zone? 

What are you testing for to determine True or False?

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/CentralConfig/Get-ConfigZone/

**Comment by katshann** [comment]
Hello Carl,
I've raised an internal ticket to get more of this information added to teh SDK docs. I'll see if I can get more info on this from the developers.
Cheers,
Kat

Reference: BRK-14442

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
