### ISSUE TITLE
Needs a download link

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#154]
Doesn't say where to get the SDK from or link to a page that does

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/

**Comment by katshann** [comment]
Hi Guy,
The CVAD developer docs have been migrated to a new system. The latest can be found at https://developer-docs.citrix.com/en-us/citrix-virtual-apps-desktops-sdk/current-release  
This page still doesn't say where to get the SDK from.  I think it's available at https://www.citrix.com/downloads/citrix-cloud/product-software/xenapp-and-xendesktop-service.html but will have to double-check that this is the correct one.
I've raised an internal ticket to add this information to the SDK docs:  BRK-14542
As we are no longer tracking issues in this GitHub repo, I'm going to close this ticket and the related work will be tracked internally.  Please use the "Send us your feedback" link on the new version of the site to raise any further cases.
Cheers,
Kat
