### ISSUE TITLE
Missing custom properties needed to create catalog

### ISSUE THREAD

**Issue by yuhual** [citrix/devdocs-issue-collector#20]
[Provide your feedback here]

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/MachineCreation/New-ProvScheme/

This page needs a major update because it misses many custom properties needed to create catalog on Azure, GCP, etc

**Comment by davidgreen99** [comment]
Citrix Virtual Apps and Desktops SDK republished as version 2103 on 29/4/21:
https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/

@yuhual Please confirm that this issue is recolved.

**Comment by davidgreen99** [comment]
Silence from reporter. Closing.
