### ISSUE TITLE
Incorrect formatting of CVAD SDK documentation articles

### ISSUE THREAD

**Issue by davidgreen99** [citrix/devdocs-issue-collector#21]
Some articles in the CVAD SDK documentation contain incorrect markdown which makes them very hard to read.

Repo lives here: https://github.com/citrix/citrix-virtual-apps-desktops-sdk

Example of the issue: See Return Values and Notes sections!
page https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/MachineCreation/Publish-ProvMasterVMImage/
raw md file: https://raw.githubusercontent.com/citrix/citrix-virtual-apps-desktops-sdk/master/docs/MachineCreation/Publish-ProvMasterVMImage.md

**Comment by davidgreen99** [comment]
Tracking in https://issues.citrite.net/browse/BRK-8304

**Comment by katshann** [comment]
Fix in progress. Until then, some cleanup with a post-generation script has improved things.

**Comment by katshann** [comment]
Hi David,

Hope things are going well. 
Some fixes were put in in BRK-8304. Further fixes being pursued in follow-on internal ticket BRK-12080. 

Workaround scripts are keeping things OK looking for now. As a result, I shall close this ticket.

Cheers,
Kat
