### ISSUE TITLE
missing format

### ISSUE THREAD

**Issue by yanlafrance** [citrix/devdocs-issue-collector#25]
Hi,
the doc when you scroll to the right side is missing the syslog format. this happened time to time

Docs URL:https://developer-docs.citrix.com/projects/netscaler-syslog-message-reference/en/12.0/

**Comment by kurtcoll** [comment]
@subbendumajumder @sreejithgs - It looks like this content exists in the later versions of the doc, but not in the 12.0 doc. Can the old doc be fixed, or is the new doc preferred?

**Comment by yanlafrance** [comment]
Hi,
I will take the new doc, but google bring me there. I didn’t find the new one

yan

Yan Lafrance
M  +1 514-942-0080


From: kurtcoll ***@***.***>
Date: Thursday, May 6, 2021 at 10:37 AM
To: citrix/devdocs-issue-collector ***@***.***>
Cc: Yan Lafrance ***@***.***>, Author ***@***.***>
Subject: Re: [citrix/devdocs-issue-collector] missing format (#25)
[CAUTION - EXTERNAL EMAIL] DO NOT reply, click links, or open attachments unless you have verified the sender and know the content is safe.

@subbendumajumder<https://github.com/subbendumajumder> @sreejithgs<https://github.com/sreejithgs> - It looks like this content exists in the later versions of the doc, but not in the 12.0 doc. Can the old doc be fixed, or is the new doc preferred?

**Comment by kurtcoll** [comment]
@yanlafrance From the page you found (or any page, for future reference), you can click "Versions" on the left and then click "Latest" to get the docs for the most up-to-date version of the product.

**Comment by yanlafrance** [comment]
I see, thx for the training this morning . Another problem I see with this excel sheet embedded into a web page, I’m currently responding to an RFP and I need to provide that list. The only way I see that I can export this list is by doing a print of the page, the print option of the browser is not that intelligent and will only show what is display at my screen. Is there a way to get the list or add that option to export ?

BTW, that’s a great support. I never expect to get a response and resolution that fast

Thank you

Yan

Yan Lafrance
M  +1 514-942-0080


From: kurtcoll ***@***.***>
Date: Thursday, May 6, 2021 at 10:50 AM
To: citrix/devdocs-issue-collector ***@***.***>
Cc: Yan Lafrance ***@***.***>, Mention ***@***.***>
Subject: Re: [citrix/devdocs-issue-collector] missing format (#25)
[CAUTION - EXTERNAL EMAIL] DO NOT reply, click links, or open attachments unless you have verified the sender and know the content is safe.

@yanlafrance<https://github.com/yanlafrance> From the page you found (or any page, for future reference), you can click "Versions" on the left and then click "Latest" to get the docs for the most up-to-date version of the product.

**Comment by kurtcoll** [comment]
@yanlafrance We don't have any plans to enhance the functionality of the site at the moment. The best I can offer is the following advice:

Download the page as a .html file (right click > save as).
Open the HTML file in notepad or something similar.
Copy the table HTML data (starts with `<div class="md-typeset__scrollwrap"><div class="md-typeset__table"><table>` and ends with `</table></div></div>`)
Paste that into an HTML to CSV or Excel convertor (like this one: https://www.convertcsv.com/html-table-to-csv.htm)
Download the resulting file.

**Comment by yanlafrance** [comment]
Thx for the tips. I will give a try

yan

Yan Lafrance
M  +1 514-942-0080


From: kurtcoll ***@***.***>
Date: Thursday, May 6, 2021 at 11:08 AM
To: citrix/devdocs-issue-collector ***@***.***>
Cc: Yan Lafrance ***@***.***>, Mention ***@***.***>
Subject: Re: [citrix/devdocs-issue-collector] missing format (#25)
[CAUTION - EXTERNAL EMAIL] DO NOT reply, click links, or open attachments unless you have verified the sender and know the content is safe.

@yanlafrance<https://github.com/yanlafrance> We don't have any plans to enhance the functionality of the site at the moment. The best I can offer is the following advice:

Download the page as a .html file (right click > save as).
Open the HTML file in notepad or something similar.
Copy the table HTML data (starts with "
" and ends with "
")
Paste that into an HTML to CSV or Excel convertor (like this one: https://www.convertcsv.com/html-table-to-csv.htm)
Download the resulting file.
