### ISSUE TITLE
inconsistent documentation

### ISSUE THREAD

**Issue by yuhual** [citrix/devdocs-issue-collector#29]
if I follow links from https://developer.cloud.com/citrixworkspace -> https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/, I don't see command "Unpublish-Provmastervmimage"  under MachineCreation

But if I go to CVAD service link https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/  "Unpublish-Provmastervmimage"  under MachineCreation is there.  

If I replace CVAD service link with CVAD on-prem URI base, the cmdlet is there https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/MachineCreation/Unpublish-ProvMasterVMImage, although the cmdlet name is still missing from left side list

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/

**Comment by kurtcoll** [comment]
@yuhual - 

Thank you for your feedback on this issue. I've added the cmdlet to the table of contents on the left side of the CVAD SDK docs.
