### ISSUE TITLE
flickering when I hover mouse over cmdlet list

### ISSUE THREAD

**Issue by yuhual** [citrix/devdocs-issue-collector#30]
I am using chrome browser and if I expand category list at left side, it will list cmdlets.  For example, if I click MachineCreation, it will have a pretty long list of cmdlet

If I want to browse the list, I hover mouse over the list and start scroll.  most of time, the list start to flicking.  Also, if I move my mouse away, the list goes back to beginning so I lost my context, i.e. the cmdlet that I was looking at.  I am not the only person have these issues.  My co-worker said they also have experienced these issues.

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/

**Comment by RMehreen** [comment]
Hello @yuhual

Thank you very much for the information and feedback you provided. Your time and effort in providing feedback is greatly appreciated. This is a known issue. We are working with our technical team to get this issue fixed.

Regards
Mehreen

**Comment by davidgreen99** [comment]
See DOCDEVSIT-255 Flickering TOC bug - notified JoseA and WilliamC.

**Comment by katshann** [comment]
Hello,
The CVAD SDK docs have moved to a new platform. The flickering issue should not occur on the new site.
Cheers,
Kat
