### ISSUE TITLE
Typo under Detailed Description

### ISSUE THREAD

**Issue by mav-cloud** [citrix/devdocs-issue-collector#31]
I think you have a typo in the sample code:
Remove-BrokerApplication -DesktopGroup \$group1 Add-RemoveApplication -DesktopGroup \$group2

should be:
Remove-BrokerApplication -DesktopGroup \$group1 Add-**Broker**Application -DesktopGroup \$group2

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Broker/Set-BrokerApplication/

**Comment by davidgreen99** [comment]
Created Jira https://issues.citrite.net/browse/BRK-8733 for engineering fix.

**Comment by davidgreen99** [comment]
BRK-8733 fixed and closed. The SDK docs article will be republished and visible soon.
