### ISSUE TITLE
Example is no help

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#32]
uses $xml but what is $xml?

Also, the cmdlet has two distinct parameter sets but these are not documented at all which also means there needs to be at least two examples.

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/CentralConfig/Import-ConfigFeatureTable/

**Comment by davidgreen99** [comment]
Created Jira https://issues.citrite.net/browse/BRK-8743
