### ISSUE TITLE
CVAD Service Remote PowerShell SDK Cmdlet Documentation contains disabled cmdlets, is missing cmdlets

### ISSUE THREAD

**Issue by nsjoseph** [citrix/devdocs-issue-collector#33]
Per the product documentation (https://docs.citrix.com/en-us/citrix-virtual-apps-desktops-service/sdk-api.html#citrix-virtual-apps-and-desktops-remote-powershell-sdk) there are numerous cmdlets that are not supported/enabled with the Remote PowerShell SDK and CVAD Service - yet they are still documented in the SDK as if they are. It seems unnecessary to have these documented if they cannot function - and could add confusion to administrators.

More importantly, cmdlets exclusive to the Remote PowerShell SDK in the Citrix.Sdk.Proxy.V1 module do not appear to be documented, including:

- Clear-XDCredentials
- Get-XDAdminAdministrator
- Get-XDAuthentication
- Get-XDCredentials
- Set-XDCredentials

I don't know if there are other Cloud exclusive cmdlets. But it feels like these things should be documented in the SDK documentation.

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/

**Comment by kurtcoll** [comment]
@davidgreen99 - Please look into this.

**Comment by davidgreen99** [comment]
Internal Jira ticket created to fix these doc issues: https://issues.citrite.net/browse/PDDADV-1006

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
