### ISSUE TITLE
Link to RFC2617 is broken

### ISSUE THREAD

**Issue by metadaddy** [citrix/devdocs-issue-collector#34]
The [plain http link](http://tools.ietf.org/html/rfc2617) returns 404; these links require https now - this one works:

https://tools.ietf.org/html/rfc2617

Docs URL:https://developer-docs.citrix.com/projects/storefront-authentication-sdk/en/latest/citrixauth-authentication-scheme/

**Comment by kurtcoll** [comment]
@davidgreen99 - Very minor fix here.

**Comment by davidgreen99** [comment]
Link corrected and article republished.
