### ISSUE TITLE
No URL for "[3] CitrixAuth Authentication Scheme v1"

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#4]
The other two footnotes have URLs, this one doesn't so looking up the authentication scheme involves a search rather than direct click.

Docs URL:https://developer-docs.citrix.com/projects/storefront-services-api/en/latest/

**Comment by davidgreen99** [comment]
Merged PR https://github.com/citrix/storefront-store-services-api/pull/1 to add link in footnote
