### ISSUE TITLE
Please format code snippets with monospaced text

### ISSUE THREAD

**Issue by metadaddy** [citrix/devdocs-issue-collector#42]
The code snippets in the Broker Filtering page (and, some other pages, such as [Post-Installation Configuration](https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Broker/about_Broker_PostInstallPreConfiguration/)) blend into the surrounding text:

> Some cmdlets operate on large quantities of data and, to reduce the overhead of sending all of that data over the network, many of the Get- cmdlets support server-side filtering of the results.
> 
> The conventional way of filtering results in PowerShell is to pipeline them into Where-Object, Select-Object, and Sort-Object, for example:
> 
> Get-<Noun> | Where { \$_.Size = 'Small' } | Sort 'Date' | Select -First 10
> 
> However, for most XenDesktop cmdlets the data is stored remotely and it would be slow and inefficient to retrieve large amounts of data over the network and then discard most of it. Instead, many of the Get- cmdlets provide filtering parameters that allow results to be processed on the server, returning only the required results.

Please consider calling out code with a monospaced font, both inline, and in blocks:

> Some cmdlets operate on large quantities of data and, to reduce the overhead of sending all of that data over the network, many of the `Get-` cmdlets support server-side filtering of the results.
> 
> The conventional way of filtering results in PowerShell is to pipeline them into `Where-Object`, `Select-Object`, and `Sort-Object`, for example:
> 
>     Get-<Noun> | Where { \$_.Size = 'Small' } | Sort 'Date' | Select -First 10
> 
> However, for most XenDesktop cmdlets the data is stored remotely and it would be slow and inefficient to retrieve large amounts of data over the network and then discard most of it. Instead, many of the `Get-` cmdlets provide filtering parameters that allow results to be processed on the server, returning only the required results.

XenDesktop also needs to be updates to CVAD :-)

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Broker/about_Broker_Filtering/

**Comment by kurtcoll** [comment]
@davidgreen99 - Please make sure the right people see this.

**Comment by katshann** [comment]
Internal issue raise for this (BRK-10552)

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
