### ISSUE TITLE
CVAD 2109

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#43]
[Provide your feedback here]
When will the docs be updated to CVAD 2109?

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/

**Comment by kurtcoll** [comment]
@davidgreen99 - Another one for you to run up the chain.

**Comment by davidgreen99** [comment]
@CarlWebster 
CVAD 2109 SDK docs now published. See https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/
