### ISSUE TITLE
Article names have wrong capitalisation and are hard to read

### ISSUE THREAD

**Issue by akvileware** [citrix/devdocs-issue-collector#46]
Hi,

The article names are difficult to understand as they do not use the standard PowerShell capitalization rules.

For instance, the article on the function `Add-BrokerMachinesToDesktopGroup` appears as `Add-Brokermachinestodesktopgroup` in the title and the table of contents widget on the left. This makes it hard to read functions in the content and find the ones I need.

I am happy to collaborate more on the issue through internal channels, my Citrix handle is akvilev.

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Broker/Add-BrokerMachinesToDesktopGroup/#add-brokermachinestodesktopgroup

**Comment by katshann** [comment]
Internal issue raised (BRK-10551)

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
