### ISSUE TITLE
Missing the rest of the sentence

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#48]
[Provide your feedback here]
"SharedImageGalleryReplicaMaximum: The maximum number of replicas for each shared image gallery version. This value is an integer greater than"

Greater than what?

Where is the rest of the sentence?

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/MachineCreation/about_Prov_CustomProperties/

**Comment by kurtcoll** [comment]
@davidgreen99 - Another one for you to coordinate with the team.

**Comment by graham-macdonald-citrix** [comment]
It should be "greater than 0".  As well the next bullet point "This property only applies..." belongs with this bullet point.  Looking at the source code, it looks correct:

```
    o   SharedImageGalleryReplicaMaximum: The maximum number of replicas for
        each shared image gallery version. This value is an integer greater than
        0. This property only applies when the UseSharedImageGallery property is
        set to True. If this property is not specified,
        SharedImageGalleryReplicaMaximum is set to 10 by default.
```

is this possibly a bug in the website rendering engine?

**Comment by CarlWebster** [comment]
It looks the same in Chrome, Edge, and Firefox.

![github](https://user-images.githubusercontent.com/7387263/140104034-b4801b32-23c5-4845-9a28-2d85578d467f.png)

**Comment by davidgreen99** [comment]
@CarlWebster We are investigating and taking action. In the meantime, full text should be:
"SharedImageGalleryReplicaMaximum: The maximum number of replicas for each shared image gallery version. This value is an integer greater than 0. This property only applies when the UseSharedImageGallery property is set to True. If this property is not specified, SharedImageGalleryReplicaMaximum is set to 10 by default."

**Comment by kurtcoll** [comment]
@davidgreen99 - I took a look at the file in question, and the bullet that has issues is split into three lines, one of which is just "0." That "0." is probably rendering out of existence on the live docs. If the three lines are combined into one, or even just the first and second line, that should resolve it.

* SharedImageGalleryReplicaMaximum: The maximum number of replicas for each shared image gallery version. This value is an integer greater than 0.  
[indent this or make it part of the previous line] This property only applies when the UseSharedImageGallery property is set to True. If this property is not specified, SharedImageGalleryReplicaMaximum is set to 10 by default.

**Comment by davidgreen99** [comment]
I concur.
Have created P1 https://issues.citrite.net/browse/PMCS-23390 which MCS team are actioning based on these suggestions>

@kurtcoll Please remind me: they get their changes into docs-incoming branch and you take it from there?

**Comment by kurtcoll** [comment]
@davidgreen99 That's the process for an incoming release doc set. For a small issue, the branch doesn't matter so much. Any branch/PR will work fine.

**Comment by katshann** [comment]
Seems like the fix made it through into the latest update of the docs. Looks OK now.
