### ISSUE TITLE
2109

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#49]
[Provide your feedback here]
When will this documentation be updated to reflect CVAD 2109?

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/MachineCreation/Get-ProvScheme/

**Comment by kurtcoll** [comment]
@davidgreen99 For the CVAD team.

**Comment by davidgreen99** [comment]
@CarlWebster I am hoping to get this published in next week.

**Comment by CarlWebster** [comment]
Thanks. Did you know the Citrix Cloud Remote PoSH SDK is already at 2112?

I explained to Jose Augustine and Yuhua Lu about my CC doc script:

I update the CC doc script infrequently because I can't keep up with what y'all are adding/changing. The CTP Cloud is on 2012, another CC is on 2103, another is on 2106, and the Remote PoSH SDK is on 2112. I can't get consistent script results when the CC brokers are all on different versions.

**Comment by davidgreen99** [comment]
2112 eh? Sounds like futureware to me! I'll investigate.

**Comment by CarlWebster** [comment]
DisplayName: Citrix CVAD Remote Powershell SDK - Registry
DisplayVersion: 7.32

All the modules have a DisplayVersion of 7.32.24925.nnnnn

**Comment by davidgreen99** [comment]
@CarlWebster Where exactly do you see version 2112?

**Comment by CarlWebster** [comment]
7.32 = 2112

Thanks


Carl Webster
Citrix Technology Professional Fellow | E2EVC Senator | IGEL VIP | Parallels VIPP | VMware vExpert 2021 |VMware vExpert EUC 2021 | VMware Influencer 100
http://www.CarlWebster.com<https://carlwebster.com/>
The Accidental Citrix Admin

**Comment by josecitrix** [comment]
Hey @CarlWebster. The versions for the cloud modules are irrelevant/insignificant. The versions change depending on how we roll code out using our canary mechanisms. We typically update the remote POSH SDK to the downloads page every 3-6 weeks. What should be important from a customer admin perspective is that Remote POSH that has been published to our downloads page should work with all CVADS subscriptions. 

I have a feature in the roadmap to add auto-update capability for Remote POSH. That would improve the admin awareness and increase the propensity to upgrade.

**Comment by davidgreen99** [comment]
@CarlWebster 
CVAD 2109 SDK docs now published. Now visible https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/

**Comment by CarlWebster** [comment]
Awesome, just in time for the 2112 release! LOL

OOPS! I don’t remember seeing this formatting issue before:

Using the Group Policy SDK
To create a virtual drive and load it with settings, type:
New-PSDrive &lt;Standard Parameters&gt; \[-PSProvider\]
CitrixGroupPolicy *-Controller* &lt;string&gt;
**New-PSDrive &lt;Standard Parameters&gt; \[-PSProvider\]
CitrixGroupPolicy ***-Controller*** &lt;string&gt;**


Thanks


Carl Webster

Citrix Technology Professional Fellow | IGEL VIP | Parallels VIPP | Experts Exchange Most Valuable Expert 2019 | VMware vExpert 2020 | VMware Influencer 100
http://www.CarlWebster.com
The Accidental Citrix Admin

**Comment by davidgreen99** [comment]
@CarlWebster Thanks for spotting that. Please confirm this is the correct formatting:

```
New-PSDrive Standard Parameters [-PSProvider]
CitrixGroupPolicy -Controller string
```

**Comment by CarlWebster** [comment]
From my CVAD V3.30 doc script:

New-PSDrive `
-psprovider citrixgrouppolicy `
-Name LocalFarmGPO `
-root \ `
-controller $AdminAddress `
-Scope “Global”

[
Webster: The Scope parameter was documented and used back in the XenApp 6.0 and 6.5 days. I have kept it in my scripts for consistency. I don’t see this parameter documented by Citrix now, but it is documented by Microsoft.

    -Scope <System.String>
        Specifies a scope for the drive. The acceptable values for this parameter are: Global, Local, and Script,
        or a number relative to the current scope. Scopes number 0 through the number of scopes. The current scope
        number is 0 and its parent is 1. For more information, see about_Scopes
        (../Microsoft.PowerShell.Core/About/about_Scopes.md).

        Required?                    false
        Position?                    named
        Default value                Local
        Accept pipeline input?       True (ByPropertyName)
        Accept wildcard characters?  false
]

From an internal document that Jose Augustin sent me:

PowerShell providers provide a user interface similar to a file system. At the top of the hierarchy is a drive, which is similar to a file system drive. The next command mounts the provider to a drive so that its objects can be accessed.

  *   The -PsProvider parameter must be specified and the value must be CitrixGroupPolicy.
  *   The -Name parameter specifies the name of the drive.
  *   The -Root parameter specifies the root of the drive in the hierarchy of the provider's object tree. Usually the root of the tree is specified.
  *   The -Controller parameter specifies the Citrix controller to use.
On-premises: Use localhost to connect to a controller running on the same machine. If a remote host is specified, the remote host must be a Citrix controller and necessary ports must be open for remotely connecting to the controller. The logon user must be also an administrator of the remote site. If remote connection is to be used, the FQDN (fully qualified distinguished name) of the remote controller with an optional port number must be specified. If no port number is specified, port 80 is used. To mount a drive for on- premises deployments, run the following command:

New-PsDrive -PsProvider CitrixGroupPolicy -Name GP -Root \ -Controller localhost

When using the PSDrive  provider for Citrix AD-based policies:

$CtxGPO = “GPO Name Seen in the GPMC”

New-PSDrive -Name ADGpoDrv -PSProvider CitrixGroupPolicy -Root \ -DomainGpo $($CtxGPO) -Scope "Global"

If the AD policy contains multiple Citrix policies, the PSDrive created has all the policy names at the top level.

Thanks


Carl Webster

Citrix Technology Professional Fellow | IGEL VIP | Parallels VIPP | Experts Exchange Most Valuable Expert 2019 | VMware vExpert 2020 | VMware Influencer 100
http://www.CarlWebster.com
The Accidental Citrix Admin

**Comment by davidgreen99** [comment]
Thanks @CarlWebster 
I have created Jira ticket https://issues.citrite.net/browse/PDDADV-1097 to track this doc improvement.

**Comment by sophiajoseraymond** [comment]
Hi Carl Webster,
We have updated the Group policy SDK usage documentation as suggested by Jose Augustin. The updated pages are live at:

-  https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/group-policy-sdk-usage/ 
-  https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/group-policy-sdk-usage/

 
Thanks,
Sophia Jose
