### ISSUE TITLE
MachinesCount

### ISSUE THREAD

**Issue by artdoherty** [citrix/devdocs-issue-collector#50]
The MachinesCount metric is described as "Number of machines in this Desktop Group at the time of consolidation".  However, MachinesCount does not count non-power managed machines in the Desktop Group - description should reflect this.

Docs URL:https://developer-docs.citrix.com/projects/monitor-service-odata-api/en/latest/api-reference/Monitor.Model/#machinescount

**Comment by kurtcoll** [comment]
@ravibharathcitrix Please coordinate with engineering to update this documentation.

**Comment by ravibharathcitrix** [comment]
@artdoherty , @kurtcoll : Thanks for bringing this up. I have updated the docs after discussing with Mahesh Vangapalli. Please see: https://developer-docs.citrix.com/projects/monitor-service-odata-api/en/latest/api-reference/Monitor.Model/#machinescount
