### ISSUE TITLE
error in the documentation

### ISSUE THREAD

**Issue by kaikos17** [citrix/devdocs-issue-collector#51]
In the Access using MS Excel PowerQuery section, replace Citrix-CustomerId = "<YourCustomerId>" with #"Citrix-CustomerId" = "<YourCustomerId>" 

Docs URL:https://developer-docs.citrix.com/projects/access-monitor-service-data-citrix-cloud/en/latest/

Best regards,
Vincent Rombau
Solution Delivery Architect
Citrix
vincent.rombau@citrix.com

**Comment by kurtcoll** [comment]
@ravibharathcitrix  - Another one for you to coordinate.

**Comment by ravibharathcitrix** [comment]
@kaikos17 , @kurtcoll , the doc has been updated after discussing with Mahesh Vangapalli. Please see https://developer-docs.citrix.com/projects/access-monitor-service-data-citrix-cloud/en/latest/
