### ISSUE TITLE
Get-Brokersite

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#57]
[Provide your feedback here]
Why do many property types have a "?"? Is the author not sure of the data types?

BaseOU (System.Guid?)
ConnectionLeasingEnabled (System.Boolean?)
DefaultMinimumFunctionalLevel (Citrix.Broker.Admin.SDK.FunctionalLevel?) 
LicensedSessionsActive (System.Int32?) [There are lots of these System.Int32?]
LicenseModel (Citrix.Broker.Admin.SDK.LicenseModel?) 
LicensingBurnInDate (System.DateTime?)

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/Get-BrokerSite/

**Comment by katshann** [comment]
Hi Carl, thanks for the feedback. Looks like this happens in some of the other articles as well. I'll raise it internally to get this looked into. Cheers, Kat.

Internal ref: BRK-10704

**Comment by katshann** [comment]
Hi Carl, I've received an answer from engineering on this question:

> 
> The '?' symbol here is part of the standard C#/.Net type definition. It denotes 'nullable' type forms of value (rather than reference) types such as ints, enums, structs etc. The question marks are correct and do not indicate any form of uncertainty.
> 
> See the MS docs at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types

Hope this is of help.  I'll have a look and see if there's a suitable place in the front part of these SDK docs to make note of this formatting convention.

**Comment by CarlWebster** [comment]
Not everyone is a C#/ .Net developer. Maybe the use of the "?" should be explained somewhere?

**Comment by katshann** [comment]
Indeed.  I'll have a look and see if there's a suitable place in the front part of these SDK docs to make note of this formatting convention.

**Comment by katshann** [comment]
Note added at the bottom of the Overview article: https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/
