### ISSUE TITLE
Missing Property

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#58]
[Provide your feedback here]
Why is the AzureAdJoinType property not documented here or the cmdlet's help text?

PS C:\Users\ctxadmin> Get-ProvScheme |select -first 1

AzureAdJoinType              : None

Also missing is ResetAdministratorPasswords  : False

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/MachineCreation/Get-ProvScheme/

**Comment by katshann** [comment]
Hi Carl, I've had a look at this and #68 about the same article. Looks like the autogenerated markdown for this hasn't been updated for a while. I'll follow up internally with the developers to see what's happening with these properties. Cheers, Kat.

**Comment by katshann** [comment]
Internal ref: PMCS-25899

**Comment by katshann** [comment]
Hi Carl,  I believe these properties are now documented in the latest version of the docs (now at https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/MachineCreation/Get-ProvScheme/) Cheers, Kat

**Comment by CarlWebster** [comment]
With HORRIBLE formatting!

ResetAdministratorPasswords <bool> Indicates whether the passwords for administrator accounts are reset on created machines. ServiceOffering <string> The service offering that the scheme uses when creating VMs in Cloud Hypervisors. SecurityGroups <string[]> The security groups that will be applied to machines created in Cloud Hypervisors. TenancyType <string> Tenancy type to be used when creating VMs in Cloud Hypervisors. (See New-ProvScheme.) AzureAdJoinType <string> Deprecated.

**Comment by katshann** [comment]
Indeed. There's a ticket to improve the formatting that is being worked. 

 (Related to https://github.com/citrix/devdocs-issue-collector/issues/42
  Internal ref: BRK-10552)
