### ISSUE TITLE
AdminFolderName Property

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#59]
[Provide your feedback here]

What is the purpose of this property?

AdminFolderName (System.String) The name of the admin folder the catalog is in (including trailing backslash), or the empty string if the catalog is at the root level

I see no way to create an admin folder via the GUI or https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Broker/New-BrokerCatalog/

I also see no way to move a machine catalog to an admin folder via the GUI or https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Broker/Set-BrokerCatalog/

How is this mysterious adminfoldername created and used?

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Broker/Get-BrokerCatalog/

**Comment by CarlWebster** [comment]
I now see the \*-BrokerAdminFolder\* cmdlets, but I still see no way to use them for a MC or DG even though the properties exist

**Comment by katshann** [comment]
Hi Carl, I've raised a ticket internally to get the information around this property improved in the SDK docs. Cheers, Kat

**Comment by katshann** [comment]
Internal ref: BRK-10703

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
