### ISSUE TITLE
"about" help

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#60]
[Provide your feedback here]
See about_Broker_Machines for more information.

Could you not make the "about_Broker_Machines" a clickable link that takes me to the specified "about" help topic?

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-service-sdk/en/latest/Broker/Get-BrokerCatalog/

**Comment by katshann** [comment]
Hi Carl, this is a great idea. I'll check with the folks who autogenerate these docs and see what can be done. Cheers, Kat

**Comment by katshann** [comment]
Internal ref: BRK-10702

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
