### ISSUE TITLE
2112

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#62]
[Provide your feedback here]
Now that you updated to 2109, when will you update to 2112? :)

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/

**Comment by katshann** [comment]
Hi Carl, apologies for the delay on responding to this. The latest docs should now reflect the 2112 version of the SDK. Cheers, Kat.

**Comment by CarlWebster** [comment]
And in a couple of weeks, we will need updating to 2203! It is a never-ending battle. I feel for you.

Thanks


Carl Webster
Citrix Technology Professional Fellow | E2EVC Senator | IGEL VIP | Parallels VIPP | VMware vExpert | VMware vExpert EUC | VMware Influencer 100
http://www.CarlWebster.com<https://carlwebster.com/>
The Accidental Citrix Admin
