### ISSUE TITLE
Display issue, content overflow 

### ISSUE THREAD

**Issue by khanjan9** [citrix/devdocs-issue-collector#64]
Please find the attached snapshot showing display issue. Thanks 
<img width="1788" alt="Screenshot 2022-01-06 at 6 06 43 PM" src="https://user-images.githubusercontent.com/28806629/148384087-4e58a6f6-80df-4086-95c0-e69fdfa9b23e.png">

Docs URL:https://developer-docs.citrix.com/projects/citrix-adc-command-reference/en/latest/network/fis/

**Comment by katshann** [comment]
Hello,

Thanks for raising this issue. We have an internal ticket open with the technical team and I shall follow up on that to see what the progress is.

Cheers,
Kat

Related issues: #30, #64, #83, #85 
Internal ticket: DOCDEVSIT-255

**Comment by katshann** [comment]
Hello,
The developer docs have now been moved to a new platform at https://developer-docs.netscaler.com/en-us/adc-command-reference-int/current-release/network/fis.html 
This new platform doesn't suffer from this issue with the content overflow.
Cheers,
Kat
