### ISSUE TITLE
Missing Properties

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#68]
[Provide your feedback here]
Why are the Warnings and WriteBackCacheDiskIndex properties not documented?

```
PS C:\Users\ctxadmin> get-provscheme -ProvisioningSchemeUid f767cc1c-6341-4027-a307-b071b04db6ad


CleanOnBoot                  : True
ControllerAddress            : {CVAD2112.LabADDomain.com}
CpuCount                     : 4
DiskSize                     : 48
HostingUnitName              : 10G
HostingUnitUid               : 87d96cf5-1e06-4493-9de6-1bb2ea02c3e6
IdentityPoolName             : W10 MCS32GB Random
IdentityPoolUid              : 81da351d-9282-4c68-8313-e3ca1e8b8434
MachineCount                 : 1
MachineProfile               :
MasterImageVM                : XDHyp:\HostingUnits\10G\W102112Master.vm\For MCS.snapshot\MCS After Windows
                               Updates.snapshot
MasterImageVMDate            : 2/21/2022 1:33:46 PM
MemoryMB                     : 8192
Metadata                     : {ImageManagementPrep_DoImagePreparation = True, ImageManagementPrep_Excluded_Steps = ,
                               ImageManagementPrep_NoAutoShutdown = False}
MetadataMap                  : {[ImageManagementPrep_DoImagePreparation, True], [ImageManagementPrep_Excluded_Steps,
                               ], [ImageManagementPrep_NoAutoShutdown, False]}
ProvisioningSchemeName       : W10 MCS32GB Random
ProvisioningSchemeUid        : f767cc1c-6341-4027-a307-b071b04db6ad
TaskId                       :
VMMetadata                   : {H, 4, s, I...}
PersonalVDiskDriveLetter     :
PersonalVDiskDriveSize       : 0
UsePersonalVDiskStorage      : False
NetworkMaps                  : {0}
Scopes                       :
DedicatedTenancy             : False
GpuTypeId                    :
ResetAdministratorPasswords  : False
SecurityGroups               : {}
ServiceOffering              :
TenancyType                  : Shared
AzureAdJoinType              :
CurrentMasterImageUid        : af1e163d-6e6e-448d-8db5-4d9b6ffdc8e9
CustomProperties             : <CustomProperties xmlns="http://schemas.citrix.com/2014/xd/machinecreation"
                               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Property
                               xsi:type="StringProperty" Name="UseManagedDisks" Value="true" /></CustomProperties>
UseFullDiskCloneProvisioning : False
UseWriteBackCache            : True
WriteBackCacheDiskSize       : 32
WriteBackCacheMemorySize     : 256
**Warnings                     : {}**
**WriteBackCacheDiskIndex      : 2**
```

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/MachineCreation/Get-ProvScheme/

**Comment by katshann** [comment]
Hi Carl, I've had a look at this and #58  about the same article. Looks like the autogenerated markdown for this hasn't been updated for a while. I'll follow up internally with the developers to see what's happening with these properties. Cheers, Kat.

**Comment by katshann** [comment]
Internal ref: PMCS-25899

**Comment by katshann** [comment]
Hi Carl,  from comments on the internal ticket and a quick eyeball of the article, I believe these two properties have now been added in the 2206 docs. Cheers, Kat

**Comment by CarlWebster** [comment]
With absolutely HORRIBLE formatting!!!

Warnings <Citrix.MachineCreation.Sdk.ProvSchemeWarning[]> Warning states that have occurred with this provisioning scheme. WriteBackCacheDiskIndex <int> The disk index for the write-back cache disk. Specify only when UseWriteBackCache is true.

**Comment by katshann** [comment]
Indeed. The formatting issue is being actively worked on. I've put an interim fix in for now. Hope this helps somewhat.

Tracking under https://github.com/citrix/devdocs-issue-collector/issues/42 (Internal ref: BRK-10552)

**Comment by CarlWebster** [comment]
I do appreciate your efforts.

**Comment by katshann** [comment]
Many thanks. Though I'm afraid my power in this matter is somewhat limited. I'm mostly a conduit for these docs and any related issues.

**Comment by CarlWebster** [comment]
With absolutely HORRIBLE formatting!!!

Warnings <Citrix.MachineCreation.Sdk.ProvSchemeWarning[]> Warning states that have occurred with this provisioning scheme. WriteBackCacheDiskIndex <int> The disk index for the write-back cache disk. Specify only when UseWriteBackCache is true.

Thanks


Carl Webster
Citrix Technology Professional Fellow | E2EVC Senator | IGEL VIP | Parallels VIPP | VMware vExpert | VMware vExpert EUC | VMware Influencer 100
http://www.CarlWebster.com<https://carlwebster.com/>
The Accidental Citrix Admin
