### ISSUE TITLE
Property layout is difficult to read

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#69]
[Provide your feedback here]
I checked in Chrome, Edge, and Firefox and this is hard to read. The layout makes it difficult to separate the property names from the descriptive text.

![getprovscheme](https://user-images.githubusercontent.com/7387263/155345457-08bfc7e2-6834-4cb8-a5f1-1cab422d5387.png)

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/MachineCreation/Get-ProvScheme/

**Comment by katshann** [comment]
Hi Carl, thanks for the feedback. I'll raise this internally and see what we can do. Cheers, Kat

**Comment by katshann** [comment]
Note to self: related to #42 
Internal ref: BRK-10552

**Comment by katshann** [comment]
Hi Carl, the ticket to fix this output is progressing. However, I've done an interim fix that I hope improves things to some degree. Cheers, Kat

**Comment by CarlWebster** [comment]
Better.

CleanOnBoot &lt;bool&gt; Indicates whether the VMs created will be reset to a clean state on each start.

ControllerAddress &lt;string[]&gt; The DNS names of the controllers associated with this provisioning scheme.

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
