### ISSUE TITLE
please make method names hyperlinks showing their usage.  

### ISSUE THREAD

**Issue by bjmgeek** [citrix/devdocs-issue-collector#72]
When browsing the documentation at

Docs URL:https://developer-docs.citrix.com/projects/citrix-hypervisor-sdk/en/latest/using/

I see lots of monospaced text such as `login_with_password`
![image](https://user-images.githubusercontent.com/460013/157502325-bece6893-6e79-4857-ab97-49d35dc9eda8.png)

It would be really useful to have that text be a hyperlink to the definition of that method with the available parameters.

**Comment by katshann** [comment]
Hello, I'll raise an internal ticket to see what can be done to add these. Cheers!

**Comment by bjmgeek** [comment]
Thanks!

**Comment by katshann** [comment]
Hello, I've been through and added links to API items that are mentioned in the text of the guide. I think I got them all. Hope this is more helpful now. Cheers, Kat
