### ISSUE TITLE
InputOBject Limit

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#75]
[Provide your feedback here]
Is there a limit to the number of machines that can be in the InoutObject?

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/Set-BrokerMachineMaintenanceMode/

**Comment by katshann** [comment]
Hello. I'll see if I can find an answer for this one and raise an internal ticket to have the information added to the SDK docs. Cheers!

**Comment by katshann** [comment]
I've received this answer: 

> There's no hard limit on the number of input objects (but there would ultimately come a point where the request would be so large that its execution could timeout). Where multiple input objects are passed they are processed in sequence.

> The timeout most likely to come into play for very long running commands is the communication timeout between SDK client & server: 10 minutes for on-premises Citrix Virtual Apps and Desktops, less for Citrix DaaS.

Internal ticket raise to add to the SDK docs: BRK-10993

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
