### ISSUE TITLE
Where are the enum lists?

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#78]
[Provide your feedback here]
Why is there no documentation for the properties that are type enum?

CurrentScheduleState
UpgradeState
UpgradeType

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/VdaUpdateService/Get-VusCatalogInfo/

**Comment by katshann** [comment]
Internal ticket raised: https://issues.citrite.net/browse/BRK-11474

**Comment by katshann** [comment]
Related to #78, #89,  #90

**Comment by katshann** [comment]
Hi Carl,  this info is in the source, so we're looking at a doc build issue here. It's being investigated, but no update for 2206. I've pasted the info in one of the related tickets. Let me know if that answers your query as an interim measure.  Cheers, Kat

**Comment by CarlWebster** [comment]
yes, it does


Carl Webster

Citrix Technology Professional Fellow | E2EVC Senator | IGEL VIP | Parallels VIPP | VMware vExpert 2021 |VMware vExpert EUC 2021 | VMware Influencer 100

http://www.CarlWebster.com<https://carlwebster.com/>

The Accidental Citrix Admin

________________________________

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally. 
However, as this issue related to a cmdlet and article that will shortly be retired. I think it's likely the internal ticket will not be progressed before that retirement.
Cheers,
Kat
