### ISSUE TITLE
Text formattng

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#79]
[Provide your feedback here]
Some of the text formatting is not correct. For example:

More comparisons are possible using advanced filtering with -Filter:

Get-<Noun> -Filter 'Capacity -ge 10gb' Get-<Noun> -Filter 'Age -ge 20 -and Age -lt 40' Get-<Noun> -Filter 'VolumeLevel -like "[123]"' Get-<Noun> -Filter 'Enabled -ne \$false' Get-<Noun> -Filter 'NullableProperty -ne \$null'

Which looks like it should have been:

More comparisons are possible using advanced filtering with -Filter:

Get-<Noun> -Filter 'Capacity -ge 10gb' 
Get-<Noun> -Filter 'Age -ge 20 -and Age -lt 40' 
Get-<Noun> -Filter 'VolumeLevel -like "[123]"' 
Get-<Noun> -Filter 'Enabled -ne \$false' 
Get-<Noun> -Filter 'NullableProperty -ne \$null'

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/about_Broker_Filtering/

**Comment by katshann** [comment]
Hello,

Thanks for your feedback. I'll make sure this is updated in the next version of the docs.

Cheers,
Kat

**Comment by katshann** [comment]
Hi Carl, there are some spacing improvements for the filtering topics in the latest docs that should hopefully make this easier to read. Cheers, Kat

**Comment by CarlWebster** [comment]
Thank you very much.

Thanks


Carl Webster
Citrix Technology Professional Fellow | E2EVC Senator | IGEL VIP | Parallels VIPP | VMware vExpert | VMware vExpert EUC | VMware Influencer 100
http://www.CarlWebster.com<https://carlwebster.com/>
The Accidental Citrix Admin
