### ISSUE TITLE
-Filter is not working as expected

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#80]
[Provide your feedback here]
According to the help text on about_broker_filtering, I should be able to use both of these commands:

Get-BrokerPowerTimeScheme -DesktopGroupUid 83 -Filter {DaysOfWeek -ne "Weekdays"}
Get-BrokerPowerTimeScheme -DesktopGroupUid 83 -Filter {DaysOfWeek -ne "Weekdays" -and DaysOfWeek -ne "WeekEnd"}
Get-BrokerPowerTimeScheme -DesktopGroupUid 83 -Filter 'DaysOfWeek -ne "Weekdays"'
Get-BrokerPowerTimeScheme -DesktopGroupUid 83 -Filter 'DaysOfWeek -ne "Weekdays" -and DaysOfWeek -ne "WeekEnd"'

but all give an error.

Get-BrokerPowerTimeScheme : Syntax of filtering clause is incorrect, or does not support use of one or more of the
specified parameters

They work using the old way of using a Where statement.

PS C:\webster> Get-BrokerPowerTimeScheme -DesktopGroupUid 83 | where {$_.DaysOfWeek -ne "Weekdays" -and $_.DaysOfWeek -ne "WeekEnd"}

DaysOfWeek          : Friday
DesktopGroupUid     : 83
DisplayName         : Friday schedule
MetadataMap         : {}
Name                : Scripted 2019_Friday schedule
PeakHalfHours       : {False, False, False, False...}
PeakHours           : {False, False, False, False...}
PoolSize            : {0, 0, 0, 0...}
PoolSizeHalfHours   : {0, 0, 0, 0...}
PoolUsingPercentage : False
Uid                 : 177

DaysOfWeek          : Monday
DesktopGroupUid     : 83
DisplayName         : Monday schedule
MetadataMap         : {}
Name                : Scripted 2019_Monday schedule
PeakHalfHours       : {False, False, False, False...}
PeakHours           : {False, False, False, False...}
PoolSize            : {1, 1, 1, 1...}
PoolSizeHalfHours   : {1, 1, 1, 1...}
PoolUsingPercentage : False
Uid                 : 173

DaysOfWeek          : Saturday
DesktopGroupUid     : 83
DisplayName         : Saturday schedule
MetadataMap         : {}
Name                : Scripted 2019_Saturday schedule
PeakHalfHours       : {False, False, False, False...}
PeakHours           : {False, False, False, True...}
PoolSize            : {1, 1, 1, 1...}
PoolSizeHalfHours   : {1, 1, 1, 1...}
PoolUsingPercentage : False
Uid                 : 178

DaysOfWeek          : Sunday
DesktopGroupUid     : 83
DisplayName         : Sunday schedule
MetadataMap         : {}
Name                : Scripted 2019_Sunday schedule
PeakHalfHours       : {False, False, False, False...}
PeakHours           : {False, False, False, False...}
PoolSize            : {2, 2, 2, 2...}
PoolSizeHalfHours   : {2, 2, 2, 2...}
PoolUsingPercentage : False
Uid                 : 179

DaysOfWeek          : Thursday
DesktopGroupUid     : 83
DisplayName         : Thursday schedule
MetadataMap         : {}
Name                : Scripted 2019_Thursday schedule
PeakHalfHours       : {False, False, False, False...}
PeakHours           : {False, False, False, False...}
PoolSize            : {4, 4, 4, 4...}
PoolSizeHalfHours   : {4, 4, 4, 4...}
PoolUsingPercentage : False
Uid                 : 174

DaysOfWeek          : Tuesday
DesktopGroupUid     : 83
DisplayName         : Tuesday schedule
MetadataMap         : {}
Name                : Scripted 2019_Tuesday schedule
PeakHalfHours       : {False, False, False, False...}
PeakHours           : {False, False, False, False...}
PoolSize            : {2, 2, 2, 2...}
PoolSizeHalfHours   : {2, 2, 2, 2...}
PoolUsingPercentage : False
Uid                 : 175

DaysOfWeek          : Wednesday
DesktopGroupUid     : 83
DisplayName         : Wednesday schedule
MetadataMap         : {}
Name                : Scripted 2019_Wednesday schedule
PeakHalfHours       : {False, False, False, False...}
PeakHours           : {False, False, False, False...}
PoolSize            : {3, 3, 3, 3...}
PoolSizeHalfHours   : {3, 3, 3, 3...}
PoolUsingPercentage : False
Uid                 : 176

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/Get-BrokerPowerTimeScheme/

**Comment by katshann** [comment]
Hi Carl,

Thank you for this feedback. I've raised a ticket with the development team to address this.

Cheers,
Kat

Internal reference: BRK-11417

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
