### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by rafaelpirolla** [citrix/devdocs-issue-collector#83]
When navigating the API on the left the scrolling behaves strangely. Tried brave, edge and firefox. It seems the scrolling position is reset when the cursor leaves the area.

Docs URL:https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/13/configuration/configuration/

**Comment by katshann** [comment]
Hello,

Thanks for raising this issue. We have an internal ticket open with the technical team and I shall follow up on that to see what the progress is.

Cheers,
Kat

Related issues: #30, #64, #83, #85 
Internal ticket: DOCDEVSIT-255

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform: https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release.html The left ToC scrolling issue should not be a problem on the new site.
Cheers,
Kat
