### ISSUE TITLE
Filtering by Multiple Tags

### ISSUE THREAD

**Issue by PIP-ITSA** [citrix/devdocs-issue-collector#84]
Please could you add a section about filtering by Tag!
It was the most obvious method to use to differentiate groups of VDAs.
For example; Odds, Evens, Prod, Dev.
A VDA could be: Odds, Prod
or  Evens, Prod
or Evens, Dev
You would wish to perform different actions to the VDA based on these four tags but two each! 
As a beginner, it took me an age to work out how to filter by multiple Tags!
Here you simply show a single Tag but suggest it is possible to search by a list!  This is not true when using the method shown here.
"-Tag" can only have a single entry, even though you suggest it simply accepts a string. 
Even the output suggests you can search by "Tags" but no.
You have to use "-Filter" {}
Even that requires each "Tag" to be specified individually;
$machines = Get-BrokerMachine  -Filter {Tag -eq 'PROD' -and Tag -eq 'EVENS'}
Many thanks
Ian
Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/Get-BrokerMachine/

**Comment by katshann** [comment]
Hi Ian,
Thank you for your feedback. I've raised an internal case for the development team to address this.
Cheers,
Kat

Internal reference: BRK-11416

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
