### ISSUE TITLE
Page flashes when scrolling and left hand side links don't work

### ISSUE THREAD

**Issue by guyrleech** [citrix/devdocs-issue-collector#85]
Please see the video in the CTP Slack post

https://citrixctp.slack.com/archives/C1ARNLG7N/p1654273113050839

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/1811/Broker/Set-BrokerHostingPowerAction/

**Comment by katshann** [comment]
Hello,

Thanks for raising this issue. We have an internal ticket open with the technical team and I shall follow up on that to see what the progress is.

Cheers,
Kat

Related issues: #30, #64, #83, #85 
Internal ticket: DOCDEVSIT-255

**Comment by katshann** [comment]
Hi Guy,
This issue should be fixed on the new developer docs publishing platform: https://developer-docs.citrix.com/en-us/citrix-virtual-apps-desktops-sdk/
However, I believe the 1811 docs are no longer available at the new location.
Cheers,
Kat

**Comment by guyrleech** [comment]
Typo "desktopss" multiple times on that page

Regards,

Guy

**Comment by katshann** [comment]
:D Yes - I've already flagged that up to the team. Hopefully fixed very shortly. Unless we are newly translating into Parseltongue.
