### ISSUE TITLE
You broke a lot of cmdlets

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#88]
[Provide your feedback here]
Since Citrix added Machine Catalog Folders to DaaS, it breaks the functionality of other cmdlets.

Get-BrokerMachine -CatalogName "SomeCatalogName" only works if the catalog is not in a folder.

If the catalog is in a folder, use Get-BrokerMachine -CatalogName "MCFolder\SomeCatalogName".

I assume this same fix is needed for any cmdlet that uses -CatalogName.

This is NOT documented in any cmdlet's help text.

For example:

CatalogName (System.String) Name of the catalog the machine is a member of.

This needs updating.

CatalogName (System.String) If the catalog is in the default root folder, the name of the catalog the machine is a member of. If the catalog is in a folder, prepend the folder name and trailing backslash to the catalog's name. For example, FolderName\TheCatalogName.

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/Broker/Get-BrokerMachine/

**Comment by katshann** [comment]
Hi Carl, thanks for the feedback and the suggested text. I've raised a ticket with the team to get this added. Cheers, Kat

Internal ticket reference: BRK-11503

**Comment by katshann** [comment]
Hi Carl,  the developers have marked this one as complete in 2209. They updated instances throughout to refer to "full path name" or "site-wide unique full path name". Hopefully this disambiguates things a little. Cheers!
