### ISSUE TITLE
Mising Enum Definitions

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#90]
[Provide your feedback here]

Why are the Enums not defined for UpgradeState and UpgradeType? What are their possible values?

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/VdaUpdateService/Get-VusMachineInfo/

**Comment by katshann** [comment]
Related to #78, #89,  #90

**Comment by katshann** [comment]
Related to #78, #89,  #90

**Comment by katshann** [comment]
Adding to internal ticket: https://issues.citrite.net/browse/BRK-11474

**Comment by katshann** [comment]
Hi Carl, I have a ticket raised with the team to add this to the SDK docs and asked them to provide this info. I'll let you know the answer as soon as I get it (for this and related tickets). Cheers, Kat

**Comment by katshann** [comment]
Hi Carl, this looks like it's an issue in the docs being built out as the info does exist in the source. Issue is still being investigated and a fix didn't make it into 2206.
Here's the raw info though:
```
        <SdkObjectProperty Name="UpgradeType" Type="Citrix.VdaUpdateService.Sdk.UpgradeType" Settable="No">
          Release type the VDA upgrades follow. Possible values are: \n
          o NotSet - Upgrade release type was not set by admin for this catalog. 
          o CR - VDA upgrades follow CR release cycles.
          o LTSR - VDA upgrades follow LTSR release cycles.
        </SdkObjectProperty>
        <SdkObjectProperty Name="UpgradeState" Type="Citrix.VdaUpdateService.Sdk.UpgradeState" Settable="No">
          Represents whether one or more VDAs in a catalog can be upgraded. Possible values are: \n
          o MissingUpgradeType - Admin has not yet set UpgradeType, which is required to figure out whether catalog
                                 can be upgraded.
          o UpgradeScheduled - Upgrade was scheduled or is in progress for this catalog.
          o UpgradeAvailable - One or more machines in this catalog can be upgraded. 
          o UpToDate - All VDAs in this catalog are on the most recently released version.
          o Unknown - Temporary state where the service is currently figuring out one of the above states.
        </SdkObjectProperty>
```
Cheers,
Kat

**Comment by katshann** [comment]
Hello,
The developer-docs have moved to a new platform and as a result feedback tickets for these docs will no longer be collected in this GitHub project. Accordingly, I shall close this ticket and the related work will be tracked internally.
Cheers,
Kat
