### ISSUE TITLE
CVAD 2206

### ISSUE THREAD

**Issue by CarlWebster** [citrix/devdocs-issue-collector#92]
[Provide your feedback here]
It is time to update for CVAD 2206

Docs URL:https://developer-docs.citrix.com/projects/citrix-virtual-apps-desktops-sdk/en/latest/

**Comment by katshann** [comment]
Hi Carl, thanks for the nudge. I set the process in motion last week to get these docs updated. I can't give a precise timeline, but hope to have this done soon.

**Comment by katshann** [comment]
Now updated.
