### ISSUE TITLE
Use PowerShell SDK link broken 

### ISSUE THREAD

**Issue by StephenLanigan** [citrix/devdocs-issue-collector#93]
Hi, 

When you click on "use PowerShell SDK" link, it brings you yo a new page saying page not found. The URL for that is https://developer-docs.citrix.com/projects/citrix-daas/en/latest/group-policy-sdk-usage/#citrix-group-policy-provider .  

This needs to be updated to https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/group-policy-sdk-usage/#citrix-group-policy-provider

Can you please fix this ASAP. 

Customer raised this issue. 

Docs URL:https://developer-docs.citrix.com/projects/citrix-daas-sdk/en/latest/

**Comment by katshann** [comment]
Hello. This link should now be fixed. Cheers!
